# Generated by Django 4.2.26 on 2025-12-01 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('is_threat', models.BooleanField(default=False)),
                ('threat_type', models.CharField(blank=True, max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IP Address',
                'verbose_name_plural': 'IP Addresses',
                'db_table': 'ip_addresses',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_addresse_ip_addr_436d55_idx'), models.Index(fields=['is_threat'], name='ip_addresse_is_thre_e1413d_idx'), models.Index(fields=['blocked_until'], name='ip_addresse_blocked_082dad_idx'), models.Index(fields=['last_seen'], name='ip_addresse_last_se_01b697_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('activity_type', models.CharField(choices=[('rapid_requests', 'Rapid Requests'), ('failed_logins', 'Failed Login Attempts'), ('unusual_location', 'Unusual Location'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('path_traversal', 'Path Traversal Attempt'), ('brute_force', 'Brute Force Attack'), ('bot_activity', 'Bot Activity'), ('malicious_file', 'Malicious File Upload')], max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspicious Activity',
                'verbose_name_plural': 'Suspicious Activities',
                'db_table': 'suspicious_activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='suspicious__ip_addr_d22003_idx'), models.Index(fields=['user'], name='suspicious__user_id_f8ca3d_idx'), models.Index(fields=['activity_type'], name='suspicious__activit_9a4782_idx'), models.Index(fields=['severity'], name='suspicious__severit_b73ee7_idx'), models.Index(fields=['is_resolved'], name='suspicious__is_reso_80f212_idx'), models.Index(fields=['timestamp'], name='suspicious__timesta_ef2a19_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.PositiveIntegerField()),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Access Log',
                'verbose_name_plural': 'IP Access Logs',
                'db_table': 'ip_access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_access_l_ip_addr_0a48ba_idx'), models.Index(fields=['timestamp'], name='ip_access_l_timesta_c52e6c_idx'), models.Index(fields=['user'], name='ip_access_l_user_id_5578f4_idx'), models.Index(fields=['status_code'], name='ip_access_l_status__11b360_idx'), models.Index(fields=['is_suspicious'], name='ip_access_l_is_susp_09033b_idx')],
            },
        ),
    ]
