# Generated by Django 4.2.7 on 2026-01-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
        ('users', '0006_alter_user_username'),
    ]

    operations = [
    ]
