# Generated by Django 4.2.7 on 2026-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_profile_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_name_c59a45_idx',
            old_name='departments_name_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_head_id_90aa66_idx',
            old_name='departments_head_idx',   
        ),
        migrations.RenameIndex(
            model_name='departmentofficeuser',
            new_name='department__user_id_32d99c_idx',
            old_name='dept_office_user_user_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentofficeuser',
            new_name='department__departm_475591_idx',
            old_name='dept_office_user_dept_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentofficeuser',
            new_name='department__office__7a7e1f_idx',
            old_name='dept_office_user_office_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentofficeuser',
            new_name='department__status_6e14c0_idx',
            old_name='dept_office_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_e78525_idx',
            old_name='notif_user_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_read_3f8c44_idx',
            old_name='notif_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_e4c995_idx',
            old_name='notif_created_idx',
        ),
        migrations.RenameIndex(
            model_name='office',
            new_name='offices_departm_835c26_idx',
            old_name='offices_department_idx',
        ),
        migrations.RenameIndex(
            model_name='office',
            new_name='offices_manager_93a428_idx',
            old_name='offices_manager_idx',
        ),
        migrations.AlterField(
            model_name='office',
            name='manager',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
