from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_status'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: _rename_indexes(schema_editor, forward=True),
            reverse_code=lambda apps, schema_editor: _rename_indexes(schema_editor, forward=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]


def _rename_indexes(schema_editor, forward: bool) -> None:
    # This migration was originally autogenerated as RenameIndex operations, but some
    # environments (notably SQLite dev DBs) don't have the old index names present.
    # Renaming conditionally avoids migration crashes.
    table_name = 'conversations'

    renames = [
        ('conversations_conver_type_idx', 'conversatio_convers_29a8ff_idx'),
        ('conversations_last_msg_idx', 'conversatio_last_me_594294_idx'),
        ('conversations_created_idx', 'conversatio_created_694913_idx'),
        ('conversations_deleted_idx', 'conversatio_is_dele_864cfb_idx'),
        ('conversations_status_idx', 'conversatio_convers_606dee_idx'),
    ]

    existing = schema_editor.connection.introspection.get_constraints(schema_editor.connection.cursor(), table_name)

    def do_rename(old: str, new: str) -> None:
        if old not in existing:
            return
        if not existing[old].get('index'):
            return

        vendor = schema_editor.connection.vendor
        q_old = schema_editor.quote_name(old)
        q_new = schema_editor.quote_name(new)
        q_table = schema_editor.quote_name(table_name)

        if vendor == 'mysql':
            schema_editor.execute(f"ALTER TABLE {q_table} RENAME INDEX {q_old} TO {q_new}")
        else:
            schema_editor.execute(f"ALTER INDEX {q_old} RENAME TO {q_new}")

    if forward:
        for old, new in renames:
            do_rename(old, new)
    else:
        for old, new in renames:
            do_rename(new, old)
