# Generated by Django 4.2.7 on 2026-01-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_conversations_conver_type_idx_conversatio_convers_29a8ff_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_convers_29a8ff_idx',
            old_name='conversations_conver_type_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_last_me_594294_idx',
            old_name='conversations_last_msg_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_created_694913_idx',
            old_name='conversations_created_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_is_dele_864cfb_idx',
            old_name='conversations_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_convers_606dee_idx',
            old_name='conversations_status_idx',
        ),
    ]
