# Generated by Django 5.2.6 on 2025-12-01 04:18

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('total_file_attachments', models.PositiveIntegerField(default=0)),
                ('first_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('most_active_hour', models.PositiveIntegerField(default=0)),
                ('most_active_day', models.PositiveIntegerField(default=0)),
                ('average_message_length', models.FloatField(default=0.0)),
                ('total_forwarded_messages', models.PositiveIntegerField(default=0)),
                ('total_edited_messages', models.PositiveIntegerField(default=0)),
                ('total_replied_messages', models.PositiveIntegerField(default=0)),
                ('average_messages_per_day', models.FloatField(default=0.0)),
                ('peak_activity_date', models.DateField(blank=True, null=True)),
                ('peak_activity_count', models.PositiveIntegerField(default=0)),
                ('total_file_size', models.BigIntegerField(default=0)),
                ('most_common_file_type', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation Analytics',
                'verbose_name_plural': 'Conversation Analytics',
                'db_table': 'conversation_analytics',
            },
        ),
        migrations.CreateModel(
            name='MessageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('has_emoji', models.BooleanField(default=False)),
                ('has_link', models.BooleanField(default=False)),
                ('has_mention', models.BooleanField(default=False)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('forward_count', models.PositiveIntegerField(default=0)),
                ('reaction_count', models.PositiveIntegerField(default=0)),
                ('time_to_first_reply', models.DurationField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message Metrics',
                'verbose_name_plural': 'Message Metrics',
                'db_table': 'message_metrics',
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('api_response_time', 'API Response Time'), ('database_query_time', 'Database Query Time'), ('websocket_latency', 'WebSocket Latency'), ('file_upload_time', 'File Upload Time'), ('message_delivery_time', 'Message Delivery Time')], max_length=30)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('user_management', 'User Management'), ('chat_messages', 'Chat Messages'), ('file_operations', 'File Operations'), ('admin_operations', 'Admin Operations')], max_length=30)),
                ('value', models.FloatField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'db_table': 'performance_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_active_users', models.PositiveIntegerField(default=0)),
                ('new_user_registrations', models.PositiveIntegerField(default=0)),
                ('total_user_logins', models.PositiveIntegerField(default=0)),
                ('total_conversations_created', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('total_groups_created', models.PositiveIntegerField(default=0)),
                ('total_files_uploaded', models.PositiveIntegerField(default=0)),
                ('total_file_storage_used', models.BigIntegerField(default=0)),
                ('average_file_size', models.FloatField(default=0.0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('peak_concurrent_users', models.PositiveIntegerField(default=0)),
                ('total_api_requests', models.PositiveIntegerField(default=0)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('suspicious_activities', models.PositiveIntegerField(default=0)),
                ('database_size', models.BigIntegerField(default=0)),
                ('media_storage_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Analytics',
                'verbose_name_plural': 'System Analytics',
                'db_table': 'system_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('total_messages_received', models.PositiveIntegerField(default=0)),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('total_groups_joined', models.PositiveIntegerField(default=0)),
                ('total_files_uploaded', models.PositiveIntegerField(default=0)),
                ('total_login_attempts', models.PositiveIntegerField(default=0)),
                ('first_activity', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('total_active_days', models.PositiveIntegerField(default=0)),
                ('average_message_length', models.FloatField(default=0.0)),
                ('most_active_hour', models.PositiveIntegerField(default=0)),
                ('most_active_day', models.PositiveIntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('average_daily_messages', models.FloatField(default=0.0)),
                ('total_forwarded_messages', models.PositiveIntegerField(default=0)),
                ('total_replied_messages', models.PositiveIntegerField(default=0)),
                ('total_edited_messages', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'db_table': 'user_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('total_session_duration', models.DurationField(default=datetime.timedelta(0))),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('conversations_joined', models.PositiveIntegerField(default=0)),
                ('files_uploaded', models.PositiveIntegerField(default=0)),
                ('first_activity_time', models.TimeField(blank=True, null=True)),
                ('last_activity_time', models.TimeField(blank=True, null=True)),
                ('active_hours_count', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'User Engagement',
                'verbose_name_plural': 'User Engagement',
                'db_table': 'user_engagement',
                'ordering': ['-date'],
            },
        ),
    ]
