# Generated by Django 5.2.6 on 2025-12-01 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemanalytics',
            index=models.Index(fields=['date'], name='system_anal_date_ccb353_idx'),
        ),
        migrations.AddIndex(
            model_name='systemanalytics',
            index=models.Index(fields=['total_active_users'], name='system_anal_total_a_b366b3_idx'),
        ),
        migrations.AddIndex(
            model_name='systemanalytics',
            index=models.Index(fields=['total_messages_sent'], name='system_anal_total_m_b43cde_idx'),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversationanalytics',
            index=models.Index(fields=['conversation'], name='conversatio_convers_65ebca_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationanalytics',
            index=models.Index(fields=['total_messages'], name='conversatio_total_m_5dd5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationanalytics',
            index=models.Index(fields=['last_message_at'], name='conversatio_last_me_f407e3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationanalytics',
            index=models.Index(fields=['average_messages_per_day'], name='conversatio_average_18f1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemetrics',
            index=models.Index(fields=['message'], name='message_met_message_41f7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemetrics',
            index=models.Index(fields=['character_count'], name='message_met_charact_10a4d0_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemetrics',
            index=models.Index(fields=['reply_count'], name='message_met_reply_c_4058db_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemetrics',
            index=models.Index(fields=['time_to_first_reply'], name='message_met_time_to_9ef11e_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['metric_type'], name='performance_metric__5267b3_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['category'], name='performance_categor_cc63a5_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['timestamp'], name='performance_timesta_79a065_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['value'], name='performance_value_00e512_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['user'], name='user_analyt_user_id_e16c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['last_activity'], name='user_analyt_last_ac_3cf7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['total_messages_sent'], name='user_analyt_total_m_bc276b_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['average_daily_messages'], name='user_analyt_average_d17a74_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['user'], name='user_engage_user_id_8dcf23_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['date'], name='user_engage_date_d2d54b_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['engagement_score'], name='user_engage_engagem_a901cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userengagement',
            unique_together={('user', 'date')},
        ),
    ]
