# Generated by Django 5.2.6 on 2025-12-01 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.group'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trash',
            name='deleted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trashed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type'], name='audit_logs_action__168beb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='audit_logs_actor_i_0badd2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type'], name='audit_logs_target__5b2fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_id'], name='audit_logs_target__483e25_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity'], name='audit_logs_severit_fc52cc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='audit_logs_ip_addr_919cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['category'], name='audit_logs_categor_27b551_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['backup_type'], name='backups_backup__1988f1_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['status'], name='backups_status_c02d44_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['created_by'], name='backups_created_98f7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmessage',
            index=models.Index(fields=['message_type'], name='system_mess_message_55c906_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmessage',
            index=models.Index(fields=['target_type'], name='system_mess_target__bf53da_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmessage',
            index=models.Index(fields=['is_sent'], name='system_mess_is_sent_379b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmessage',
            index=models.Index(fields=['sent_at'], name='system_mess_sent_at_69d958_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmessage',
            index=models.Index(fields=['expires_at'], name='system_mess_expires_a60a10_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['key'], name='system_sett_key_052b30_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['category'], name='system_sett_categor_db5b74_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['is_public'], name='system_sett_is_publ_c2e919_idx'),
        ),
        migrations.AddIndex(
            model_name='trash',
            index=models.Index(fields=['item_type'], name='trash_item_ty_bc6648_idx'),
        ),
        migrations.AddIndex(
            model_name='trash',
            index=models.Index(fields=['deleted_by'], name='trash_deleted_10c844_idx'),
        ),
        migrations.AddIndex(
            model_name='trash',
            index=models.Index(fields=['deleted_at'], name='trash_deleted_39fbb6_idx'),
        ),
    ]
