# Generated by Django 4.2.26 on 2025-12-02 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('welcome', 'Welcome'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('announcement', 'Announcement'), ('support', 'Support'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'db_table': 'message_templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='message_tem_categor_4db5d6_idx'), models.Index(fields=['created_by'], name='message_tem_created_de4c9b_idx'), models.Index(fields=['created_at'], name='message_tem_created_05766e_idx')],
            },
        ),
    ]
