# Generated by Django 4.2.7 on 2026-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_remove_usermoderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_FAILED_LOGIN', 'Failed User Login'), ('PASSWORD_CHANGED', 'Password Changed'), ('EMAIL_VERIFIED', 'Email Verified'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('USER_APPROVED', 'User Approved'), ('USER_SUSPENDED', 'User Suspended'), ('USER_BANNED', 'User Banned'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('FORCE_LOGOUT', 'Force Logout'), ('ROLE_CHANGED', 'Role Changed'), ('PERMISSION_GRANTED', 'Permission Granted'), ('PERMISSION_REVOKED', 'Permission Revoked'), ('CONVERSATION_CREATED', 'Conversation Created'), ('CONVERSATION_UPDATED', 'Conversation Updated'), ('CONVERSATION_DELETED', 'Conversation Deleted'), ('MESSAGE_SENT', 'Message Sent'), ('MESSAGE_EDITED', 'Message Edited'), ('MESSAGE_DELETED', 'Message Deleted'), ('MESSAGE_FORWARDED', 'Message Forwarded'), ('GROUP_CREATED', 'Group Created'), ('GROUP_UPDATED', 'Group Updated'), ('GROUP_DELETED', 'Group Deleted'), ('GROUP_JOINED', 'Group Joined'), ('GROUP_LEFT', 'Group Left'), ('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('FILE_UPLOADED', 'File Uploaded'), ('FILE_DELETED', 'File Deleted'), ('FILE_DOWNLOADED', 'File Downloaded'), ('SYSTEM_SETTINGS_CHANGED', 'System Settings Changed'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_RESTORED', 'Backup Restored'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('SECURITY_BREACH', 'Security Breach'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('DATA_EXPORTED', 'Data Exported'), ('REPORT_GENERATED', 'Report Generated'), ('ITEM_MOVED_TO_TRASH', 'Item Moved to Trash'), ('ITEM_RESTORED', 'Item Restored'), ('PERMANENT_DELETE', 'Permanent Delete')], max_length=50),
        ),
    ]
