# Generated by Django 4.2.7 on 2026-01-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_message_templates_and_admin_outgoing_messages'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminoutgoingmessage',
            new_name='admin_outgo_type_71d486_idx',
            old_name='admin_outgo_type_6ccab2_idx',
        ),
        migrations.RenameIndex(
            model_name='adminoutgoingmessage',
            new_name='admin_outgo_status_9aa420_idx',
            old_name='admin_outgo_status_1c96b2_idx',
        ),
        migrations.RenameIndex(
            model_name='adminoutgoingmessage',
            new_name='admin_outgo_priorit_2d91a3_idx',
            old_name='admin_outgo_priority_7fcf0f_idx',
        ),
        migrations.RenameIndex(
            model_name='adminoutgoingmessage',
            new_name='admin_outgo_sent_at_17857c_idx',
            old_name='admin_outgo_sent_at_8d3f4d_idx',
        ),
        migrations.RenameIndex(
            model_name='messagetemplate',
            new_name='message_tem_categor_4db5d6_idx',
            old_name='message_tem_category_0efc7d_idx',
        ),
        migrations.RenameIndex(
            model_name='messagetemplate',
            new_name='message_tem_created_05766e_idx',
            old_name='message_tem_created__e39f0e_idx',
        ),
    ]
