# Generated by Django 4.2.7 on 2026-01-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_rename_admin_outgo_type_6ccab2_idx_admin_outgo_type_71d486_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='source_tab',
            field=models.CharField(choices=[('USERS', 'Users'), ('CHAT', 'Chat'), ('DEPARTMENTS', 'Departments'), ('MESSAGE_TEMPLATES', 'Message Templates'), ('ROLES_PERMISSIONS', 'Roles & Permissions'), ('SETTINGS', 'Settings'), ('AUDIT_LOGS', 'Audit Logs'), ('BACKUP', 'Backup'), ('ANALYTICS', 'Analytics')], default='USERS', help_text='Admin dashboard tab where the item was deleted from', max_length=30),
        ),
        migrations.AlterField(
            model_name='trash',
            name='item_type',
            field=models.CharField(choices=[('USER', 'User'), ('CONVERSATION', 'Conversation'), ('MESSAGE', 'Message'), ('GROUP', 'Group'), ('FILE', 'File'), ('DEPARTMENT', 'Department'), ('OFFICE', 'Office'), ('MESSAGE_TEMPLATE', 'Message Template'), ('ROLE', 'Role')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='trash',
            index=models.Index(fields=['source_tab'], name='trash_source__0e3d01_idx'),
        ),
    ]
