# Generated by Django 5.2.6 on 2025-12-01 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='chat.ConversationParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='chat.group'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.group'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation'], name='conversatio_convers_d44fde_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user'], name='conversatio_user_id_4a2524_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['last_read_at'], name='conversatio_last_re_421e10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='groups_name_2de3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_type'], name='groups_group_t_30329f_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_by'], name='groups_created_0db857_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['last_activity'], name='groups_last_ac_dde2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_deleted'], name='groups_is_dele_47bc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type'], name='conversatio_convers_29a8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='conversatio_last_me_594294_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='conversatio_created_694913_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_deleted'], name='conversatio_is_dele_864cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group'], name='group_membe_group_i_d2cebc_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user'], name='group_membe_user_id_88c209_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['role'], name='group_membe_role_a6fc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['status'], name='group_membe_status_7630e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation'], name='messages_convers_8904b4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='messages_sender__6ae55a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='messages_timesta_ab821b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='messages_message_5af74b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted'], name='messages_is_dele_54348c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reply_to'], name='messages_reply_t_313c91_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['message'], name='attachments_message_f05d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_type'], name='attachments_file_ty_5fd764_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_at'], name='attachments_uploade_9d85ce_idx'),
        ),
    ]
