"""
Django settings for offchat_backend project.
Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Import decouple with fallback for IDE compatibility
try:
    # Try importing decouple
    from decouple import config  # type: ignore[import]
    DECOUPLE_AVAILABLE = True
except (ImportError, ModuleNotFoundError):
    # Fallback implementation for when decouple is not available or IDEs can't resolve it
    import warnings
    warnings.warn("decouple not available, using os.environ fallback")
    
    def config(key, default=None, cast=None):
        """Fallback config function using os.environ"""
        value = os.environ.get(key, default)
        if cast and value is not None:
            if cast == bool:
                if isinstance(value, str):
                    return value.lower() in ('true', '1', 'yes', 'on')
                return bool(value)
            elif cast == int:
                return int(value)
            elif callable(cast):
                return cast(value)
            # For non-callable types (like list, str, etc.), apply cast directly
            elif not callable(cast):
                if isinstance(value, cast):
                    return value
                return cast(value)
        return value
    
    DECOUPLE_AVAILABLE = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY', 
    default='django-insecure-change-this-in-production-8x9k2m4n7p5q8r1s6t3w9v0z5a8b2e5f0g1h3i4j6k7l9m0n1o2p3q4r5s6t7u8v9w0x1y2z3'  # Temporary development key
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,192.168.2.9,192.168.2.33,testserver', cast=lambda v: [s.strip() for s in v.split(',')])

# CORS settings for React frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev server
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite dev server
    "http://127.0.0.1:5173",
    "http://localhost:4173",  # Alternative Vite port
    "http://127.0.0.1:4173",
    "http://localhost:8081",  # Vite dev server (auto-assigned)
    "http://127.0.0.1:8081",
    "http://localhost:8082",  # Vite dev server (current port)
    "http://127.0.0.1:8082",
    "http://localhost:8080",  # Alternative Vite port
    "http://127.0.0.1:8080",
    # Network access for external devices
    "http://192.168.2.9:5173",  # React dev server on network
    "http://192.168.2.9:8082",  # React dev server on network
    "http://192.168.2.9:8080",  # Alternative React port on network
    "http://192.168.2.9:8081",  # Alternative React port on network
    "http://192.168.2.33:5173",  # React dev server on network (new IP)
    "http://192.168.2.33:8082",  # React dev server on network (new IP)
    "http://192.168.2.33:8080",  # Alternative React port on network (new IP)
    "http://192.168.2.33:8081",  # Alternative React port on network (new IP)
]

CORS_ALLOW_CREDENTIALS = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'channels',
    'django_celery_beat',
    # 'silk',  # Commented out until dependency is installed
    
    # Local apps
    'users',
    'chat',
    'admin_panel',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Custom middleware for security - Temporarily disabled for debugging
    # 'users.middleware.SecurityHeadersMiddleware',
    # 'users.middleware.IPTrackingMiddleware',  # Enhanced IP tracking for security
    # 'users.middleware.RateLimitMiddleware',
    # 'users.middleware.BlacklistValidationMiddleware',
    # 'users.middleware.SessionManagementMiddleware',
    # 'users.middleware.ActivityTrackingMiddleware',
    
    # Silk for profiling (development only) - Commented out until dependency is installed
    # 'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'offchat_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Django Channels Configuration
ASGI_APPLICATION = 'offchat_backend.asgi.application'

# WebSocket channel layer configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],
        },
    } if not DEBUG else {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

WSGI_APPLICATION = 'offchat_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.BlacklistValidatingJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Commented out until dependency is installed
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@offchat.com')

# Redis Configuration
REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL if not DEBUG else 'memory://'
CELERY_RESULT_BACKEND = REDIS_URL if not DEBUG else 'cache+memory://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TASK_ALWAYS_EAGER = DEBUG  # Execute tasks synchronously in development

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'offchat_backend': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'chat': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'users': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'admin_panel': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'analytics': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    } if not DEBUG else {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Session Configuration (Changed to database sessions for development)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# In development, disable some security features
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0

# Silk Configuration (Development profiling) - Commented out until dependency is installed
# if DEBUG:
#     INSTALLED_APPS += ['silk', ]
#     MIDDLEWARE += ['silk.middleware.SilkyMiddleware', ]
#     SILKY_PYTHON_PROFILER_RESULT_BINARY_FILENAME = 'test_profile.prof'

# Rate Limiting Configuration
RATELIMIT_USE_CACHE = 'default'

# Advanced Rate Limiting Settings
RATE_LIMIT_CONFIG = {
    'auth': {
        'requests': 5,  # 5 requests
        'window': 300,  # 5 minutes
        'block_duration': 900,  # 15 minutes
    },
    'api': {
        'requests': 100,  # 100 requests
        'window': 3600,  # 1 hour
        'block_duration': 3600,  # 1 hour
    },
    'upload': {
        'requests': 10,  # 10 uploads
        'window': 3600,  # 1 hour
        'block_duration': 1800,  # 30 minutes
    },
    'general': {
        'requests': 200,  # 200 requests
        'window': 3600,  # 1 hour
        'block_duration': 1800,  # 30 minutes
    },
}

# Abuse Prevention Settings
ABUSE_PREVENTION = {
    'rapid_fire_threshold': 50,  # 50 requests in 60 seconds
    'rapid_fire_window': 60,  # 60 seconds
    'error_spike_threshold': 20,  # 20 errors in 5 minutes
    'error_spike_window': 300,  # 5 minutes
    'enable_bot_detection': True,
    'block_suspicious_ips': True,
}

# IP Whitelist (for admin IPs, etc.)
IP_WHITELIST = []  # Add IP addresses that should bypass rate limiting

# Blacklisted User Agents
BLACKLISTED_USER_AGENTS = [
    'bot', 'crawler', 'spider', 'scraper',
    'curl', 'wget', 'python-requests',
]

# Admin Settings
ADMIN_SITE_HEADER = "OffChat Admin"
ADMIN_SITE_TITLE = "OffChat Admin Portal"
ADMIN_INDEX_TITLE = "Welcome to OffChat Admin Portal"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# User Model
AUTH_USER_MODEL = 'users.User'
