# Generated by Django 5.2.6 on 2025-12-01 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_FAILED_LOGIN', 'Failed User Login'), ('PASSWORD_CHANGED', 'Password Changed'), ('EMAIL_VERIFIED', 'Email Verified'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('USER_APPROVED', 'User Approved'), ('USER_SUSPENDED', 'User Suspended'), ('USER_BANNED', 'User Banned'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('FORCE_LOGOUT', 'Force Logout'), ('ROLE_CHANGED', 'Role Changed'), ('PERMISSION_GRANTED', 'Permission Granted'), ('PERMISSION_REVOKED', 'Permission Revoked'), ('CONVERSATION_CREATED', 'Conversation Created'), ('CONVERSATION_UPDATED', 'Conversation Updated'), ('CONVERSATION_DELETED', 'Conversation Deleted'), ('MESSAGE_SENT', 'Message Sent'), ('MESSAGE_EDITED', 'Message Edited'), ('MESSAGE_DELETED', 'Message Deleted'), ('MESSAGE_FORWARDED', 'Message Forwarded'), ('GROUP_CREATED', 'Group Created'), ('GROUP_UPDATED', 'Group Updated'), ('GROUP_DELETED', 'Group Deleted'), ('GROUP_JOINED', 'Group Joined'), ('GROUP_LEFT', 'Group Left'), ('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('FILE_UPLOADED', 'File Uploaded'), ('FILE_DELETED', 'File Deleted'), ('FILE_DOWNLOADED', 'File Downloaded'), ('SYSTEM_SETTINGS_CHANGED', 'System Settings Changed'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_RESTORED', 'Backup Restored'), ('SYSTEM_MESSAGE_SENT', 'System Message Sent'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('SECURITY_BREACH', 'Security Breach'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('DATA_EXPORTED', 'Data Exported'), ('REPORT_GENERATED', 'Report Generated'), ('ITEM_MOVED_TO_TRASH', 'Item Moved to Trash'), ('ITEM_RESTORED', 'Item Restored'), ('PERMANENT_DELETE', 'Permanent Delete')], max_length=50)),
                ('description', models.TextField()),
                ('target_type', models.CharField(choices=[('USER', 'User'), ('CONVERSATION', 'Conversation'), ('MESSAGE', 'Message'), ('GROUP', 'Group'), ('FILE', 'File'), ('SYSTEM', 'System'), ('AUTH', 'Authentication')], max_length=20)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('users', 'Users Only'), ('chats', 'Chats Only'), ('messages', 'Messages Only')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('announcement', 'Announcement'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('update', 'Update'), ('security', 'Security Alert')], max_length=20)),
                ('target_type', models.CharField(choices=[('all_users', 'All Users'), ('active_users', 'Active Users'), ('group', 'Specific Group'), ('user', 'Specific User')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_persistent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Message',
                'verbose_name_plural': 'System Messages',
                'db_table': 'system_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('chat', 'Chat'), ('email', 'Email'), ('backup', 'Backup')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('USER', 'User'), ('CONVERSATION', 'Conversation'), ('MESSAGE', 'Message'), ('GROUP', 'Group'), ('FILE', 'File')], max_length=20)),
                ('item_id', models.CharField(max_length=255)),
                ('item_data', models.JSONField(blank=True, default=dict)),
                ('delete_reason', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trash Item',
                'verbose_name_plural': 'Trash Items',
                'db_table': 'trash',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
