# Generated by Django 4.2.7 on 2025-12-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_moderation_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_status_e41323_idx',
            old_name='content_re_status_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_content_a13319_idx',
            old_name='content_re_content_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_priorit_0594f7_idx',
            old_name='content_re_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_created_f142e9_idx',
            old_name='content_re_created_idx',
        ),
        migrations.RenameIndex(
            model_name='flaggedmessage',
            new_name='flagged_mes_status_ce0ccc_idx',
            old_name='flagged_mes_status_idx',
        ),
        migrations.RenameIndex(
            model_name='flaggedmessage',
            new_name='flagged_mes_reason_16aa39_idx',
            old_name='flagged_mes_reason_idx',
        ),
        migrations.RenameIndex(
            model_name='flaggedmessage',
            new_name='flagged_mes_reporte_92afcf_idx',
            old_name='flagged_mes_reported_idx',
        ),
        migrations.RenameIndex(
            model_name='flaggedmessage',
            new_name='flagged_mes_sender__c60fd9_idx',
            old_name='flagged_mes_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoderation',
            new_name='user_modera_user_id_7a9db8_idx',
            old_name='user_moder_user_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoderation',
            new_name='user_modera_action__4174f9_idx',
            old_name='user_moder_action_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoderation',
            new_name='user_modera_status_fae990_idx',
            old_name='user_moder_status_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoderation',
            new_name='user_modera_created_8b0e13_idx',
            old_name='user_moder_created_idx',
        ),
    ]
