# Generated by Django 4.2.7 on 2026-01-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_flaggedmessage_contentreview'),
        ('admin_panel', '0007_rename_content_re_status_idx_content_rev_status_e41323_idx_and_more'),
    ]

    operations = [
    ]
