# Generated by Cascade on 2026-01-22

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100, blank=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='message_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminOutgoingMessage',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('type', models.CharField(choices=[('system', 'System'), ('broadcast', 'Broadcast'), ('targeted', 'Targeted')], max_length=20)),
                ('content', models.TextField()),
                ('recipients', models.JSONField(default=list, blank=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='admin_outgoing_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_outgoing_messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['category'], name='message_tem_category_0efc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['created_at'], name='message_tem_created__e39f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminoutgoingmessage',
            index=models.Index(fields=['type'], name='admin_outgo_type_6ccab2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminoutgoingmessage',
            index=models.Index(fields=['status'], name='admin_outgo_status_1c96b2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminoutgoingmessage',
            index=models.Index(fields=['priority'], name='admin_outgo_priority_7fcf0f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminoutgoingmessage',
            index=models.Index(fields=['sent_at'], name='admin_outgo_sent_at_8d3f4d_idx'),
        ),
    ]
