# Generated by Django 5.2.6 on 2025-12-01 04:39
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], max_length=20)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklisted Token',
                'verbose_name_plural': 'Blacklisted Tokens',
                'db_table': 'blacklisted_tokens',
                'ordering': ['-blacklisted_at'],
                'indexes': [models.Index(fields=['token'], name='blacklisted_token_d070ae_idx'), models.Index(fields=['user'], name='blacklisted_user_id_a5837f_idx'), models.Index(fields=['token_type'], name='blacklisted_token_t_7317ed_idx'), models.Index(fields=['blacklisted_at'], name='blacklisted_blackli_bd04a9_idx'), models.Index(fields=['expires_at'], name='blacklisted_expires_d1bb66_idx')],
            },
        ),
    ]
