# Generated by Django 4.2.7 on 2025-12-07 05:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_trash'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trashitem',
            new_name='trash_items_item_ty_bc7700_idx',
            old_name='trash_item_type_idx',
        ),
        migrations.RenameIndex(
            model_name='trashitem',
            new_name='trash_items_deleted_90d9b8_idx',
            old_name='trash_deleted_at_idx',
        ),
        migrations.RenameIndex(
            model_name='trashitem',
            new_name='trash_items_expires_2b60c2_idx',
            old_name='trash_expires_at_idx',
        ),
    ]
