# Generated by Django 4.2.7 on 2025-12-21 08:32
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_rename_trash_item_type_idx_trash_items_item_ty_bc7700_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, dots, underscores, hyphens, and spaces.', regex='^[\\w.\\- ]+$')]),
        ),
    ]
