# Generated by Django 4.2.7 on 2026-01-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_moderator_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__moderat_b5120b_idx',
            old_name='moderation_moderator_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__target__c845a9_idx',
            old_name='moderation_target_user_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__action__4ba523_idx',
            old_name='moderation_action_type_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__is_acti_0dbf04_idx',
            old_name='moderation_is_active_idx',
        ),
    ]
